server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: producer-error-handling
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    stream:
      bindings:
        updateOrder:
          destination: updateOrder
          contentType: application/json
          group: producerGroup
          producer:
            error-channel-enabled: true
            partitionCount: 1
      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true
          replicationFactor: 1
          requiredAcks: all
          headerMapperBeanName: headerMapper
          producer-properties:
            delivery:
              timeout:
                ms: 5000
            request:
              timeout:
                ms: 5000
        bindings:
          updateOrder:
            producer:
              record-metadata-channel: orderUpdateMeta
              sync: false

#logging:
#  level:
#    org:
#      springframework.integration: TRACE
#      springframework.boot: TRACE