server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: consumer-error-handling
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    function:
      definition: orderConsumer
    stream:
      bindings:
        orderConsumer-in-0:
          destination: updateOrder
          contentType: application/json
          group: test
          error-handler-definition: orderErrorHandler
      kafka:
        binder:
          brokers: localhost:9092
          requiredAcks: all
          headerMapperBeanName: headerMapper
#        bindings:
#          consumer-in-0:
#            consumer:
#              common-error-handler-bean-name: commonOrderErrorHandler
#logging:
#  level:
#    org:
#      springframework.integration: TRACE
#      springframework.boot: TRACE