server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: producer-handling
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    stream:
      output-bindings: updateOrder;updateSecondOrder
      bindings:
        updateOrder:
          destination: UPDATE_ORDER
          contentType: application/json
          group: producerGroup
          producer:
            error-channel-enabled: true
            partitionCount: 1
        updateSecondOrder:
          destination: UPDATE_SECOND_ORDER
          contentType: application/json
          group: producerGroup
          producer:
            partitionCount: 1
      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true
          replicationFactor: 1
          requiredAcks: all
          headerMapperBeanName: headerMapper
          producer-properties:
            delivery:
              timeout:
                ms: 5000                # The value of this config should be greater than or equal to the sum of request.timeout.ms and linger.ms. https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html
            request:
              timeout:
                ms: 5000
        bindings:
          updateOrder:
            producer:
              record-metadata-channel: updateOrderSuccessChannel
              sync: false
          updateSecondOrder:
            producer:
              record-metadata-channel: updateSecondSuccessChannel
              sync: false

#logging:
#  level:
#    org:
#      springframework.integration: TRACE
#      springframework.boot: TRACE