name: Test Gradle Build
on:
  push:
  workflow_dispatch:
 # schedule:
 #   - cron: 0 0 * * * # daily
jobs:
  producer-handling-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: producer-handling
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - uses: gradle/actions/setup-gradle@v4
      id: setup-gradle
      with:
        gradle-version: 8.14.2
    - run: gradle clean bootJar check
    - run: echo "The release-candidate version was ${{ steps.setup-gradle.outputs.gradle-version }}"
